version: '3'

services:
  payment:
    image: bmblumenfeld/payment
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  description:
    image: camnix/description
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  load:
    image: camnix/expanded_description
    depends_on:
      - 'database'
    ports:
      - '3005:3005'

  feedback:
    image: uhan19/feedback_feedback
    depends_on:
      - 'database'
    ports: 
      - '3002:3002'

  compare:
    image: jsonbao/compare
    ports: 
      - '3004:3004'

  proxy:
    build: ./
    depends_on: 
      - 'payment'
      - 'description'
      - 'load'
      - 'feedback'
      - 'compare'
    ports: 
      - '3000:3000'
  
  database:
    image: mongo:latest
